topic:
  name: employee-avro
  
  
server:
  port: 8082
  

spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
#      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema:
          registry:
            url: http://127.0.0.1:8081
            
    consumer:
#      bootstrap-servers: 127.0.0.1:9092
      group-id: employee-avro-cg
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
      properties:
        schema:
          registry:
            url: http://127.0.0.1:8081
        specific:
          avro:
            reader: true